[package]
name = "http-server"
version = "0.1.0"
authors = ["Romain Desarzens <hib.pub@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
http = "0.2.3"
mime = "0.3"